repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-ast
      - id: check-yaml

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.25.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint

  - repo: https://github.com/dnephin/pre-commit-golang.git
    rev: master
    hooks:
      - id: go-build
      - id: golangci-lint
      - id: go-unit-tests

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: circleci-config-validate
      - id: forbid-binary

  - repo: https://github.com/Lucas-C/pre-commit-hooks-go.git
    rev: v1.0.1
    hooks:
      - id: checkmake
